---
title: "example"
author: "Lancelot Ravier"
date: "2024-11-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# create models
m1 = lm(anscombe$y1~anscombe$x1)
m2 = lm(anscombe$y2~anscombe$x2)
m3 = lm(anscombe$y3~anscombe$x3)
m4 = lm(anscombe$y4~anscombe$x4)

# model details
summary(m1)
summary(m2)
summary(m3)
summary(m4)

# plot
layout(matrix(1:4,2), respect=TRUE)
plot(anscombe$x1,anscombe$y1, xlim = c(3, 19), ylim = c(3, 13), main=paste0("m1 R^2=", signif(summary(m1)$r.squared, 2)*100, "%, y=", signif(m1$coefficients[1], 3), "+", signif(m1$coefficients[2], 3), "x")) ; abline(m1, col=2)
plot(anscombe$x2,anscombe$y2, xlim = c(3, 19), ylim = c(3, 13), main=paste0("m2 R^2=", signif(summary(m2)$r.squared, 2)*100, "%, y=", signif(m2$coefficients[1], 3), "+", signif(m2$coefficients[2], 3), "x")) ; abline(m2, col=2)
plot(anscombe$x3,anscombe$y3, xlim = c(3, 19), ylim = c(3, 13), main=paste0("m3 R^2=", signif(summary(m3)$r.squared, 2)*100, "%, y=", signif(m3$coefficients[1], 3), "+", signif(m3$coefficients[2], 3), "x")) ; abline(m3, col=2)
plot(anscombe$x4,anscombe$y4, xlim = c(3, 19), ylim = c(3, 13), main=paste0("m4 R^2=", signif(summary(m4)$r.squared, 2)*100, "%, y=", signif(m4$coefficients[1], 3), "+", signif(m4$coefficients[2], 3), "x")) ; abline(m4, col=2)
```

```{r}
data(CO2)
d = CO2[CO2$Type=="Quebec", ]
head(d)
m1 = lm(d$uptake~d$conc)
m2 = lm(d$uptake~log10(d$conc))

layout(matrix(1:2, 1), respect=TRUE)
plot(d$conc, d$uptake, main=paste0("uptake~conc R^2=", signif(summary(m1)$r.squared, 2)*100, "%"))
abline(m1, col=2)
plot(log10(d$conc), d$uptake, main=paste0("uptake~log10(conc) R^2=", signif(summary(m2)$r.squared, 2)*100, "%"))
abline(m2, col=2)

summary(m1)
summary(m2)

layout(1, respect=TRUE)
results = list()
for(a in 30:50) {
  for(k in 0:400) {
    t = d$conc
    Y = a*(1-2^(-t/k))
    # points(t,Y, col=2)
    res = d$uptake - Y
    eqm = sum(res^2) / length(res)
    results[[length(results)+1]] = c(a=a, k=k, eqm=eqm)
  }
}
results = as.data.frame(do.call(rbind, results))


r = results[results$eqm==min(results$eqm),]
a = r[["a"]]
k = r[["k"]]

t = d$conc
Y = a*(1-2^(-t/k))



sc_reg = sum((d$uptake - mean(d$uptake))^2)
sc_res = sum((d$uptake - Y)^2)
sc_tot = sc_res + sc_reg
r2 = sc_reg / sc_tot
r2
a
k

plot(d$conc, d$uptake, main=paste0("uptake=", a, "*(1-2^(-conc/", k, ")) R^2=", signif(r2, 2)*100, "% "))
lines(t,Y, col=2)
```
```{r}
set.seed(1)
d = d_mass_cats_10 = MASS::cats[sample(1:nrow(MASS::cats),10),]
m = lm(Hwt~Bwt, d)

summary(m)
res1 <- residuals(m)
qqnorm(res1)
qqline(res1, col = 'red')
```
```{r}
set.seed(1)
ks.test(rnorm(100), rnorm(100))
```

